# Generated by Django 5.2.7 on 2025-10-23 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_complaint_alter_appointment_options_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointments.appointment', verbose_name='Qabul'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kassir'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], max_length=20, verbose_name='Usul'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Kvitansiya №'),
        ),
    ]
