# Generated by Django 5.2.7 on 2025-10-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Klinika', max_length=200)),
                ('clinic_address', models.CharField(blank=True, max_length=255)),
                ('clinic_phone', models.CharField(blank=True, max_length=50)),
                ('receipt_footer', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
