# Generated by Django 5.2.7 on 2025-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Sozlama', 'verbose_name_plural': 'Sozlamalar'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='clinic_name',
            field=models.CharField(default='Klinika', max_length=200, verbose_name='Klinika nomi'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='clinic_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='receipt_footer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kvitansiya ost qismi'),
        ),
    ]
