# Generated by Django 5.2.7 on 2025-10-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_setting_options_alter_setting_clinic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='receipt_serial',
            field=models.PositiveIntegerField(default=0, verbose_name='Hujjat ketma-ket raqami'),
        ),
    ]
