# Generated by Django 5.2.7 on 2025-10-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_setting_receipt_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='last_cleanup',
            field=models.DateField(blank=True, null=True, verbose_name='Oxirgi tozalash kuni'),
        ),
    ]
