# Generated by Django 5.2.7 on 2025-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('admin', 'Admin'), ('doctor', 'Shifokor'), ('staff', 'Qabulxona')], default='staff', max_length=20, verbose_name='Rol'),
        ),
    ]
