# Generated by Django 5.2.7 on 2025-10-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_alter_doctor_options_alter_doctor_department_and_more'),
        ('patients', '0002_alter_patient_options_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Shikoyat nomi')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shikoyat',
                'verbose_name_plural': 'Shikoyatlar',
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Qabul', 'verbose_name_plural': 'Qabullar'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor', verbose_name='Shifokor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Bemor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Navbatda'), ('in_progress', 'Qabulda'), ('done', 'Tugallangan')], default='waiting', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Vaqt'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.complaint', verbose_name='Shikoyat'),
        ),
    ]
