# Generated by Django 5.2.7 on 2025-10-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_complaint_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doc_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hujjat raqami'),
        ),
    ]
