# Generated by Django 5.2.7 on 2025-10-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='complaint',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
