# Generated by Django 5.2.7 on 2025-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Shifokor', 'verbose_name_plural': 'Shifokorlar'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=255, verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='F.I.Sh.'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='room_number',
            field=models.CharField(max_length=30, verbose_name='Xona'),
        ),
    ]
